frameworkVersion: "3"
service: "serverless-offline-local-authorizers-examples-simple"

configValidationMode: warn

plugins:
  - serverless-offline-local-auth-plugin
  - serverless-offline
custom:
  serverless-offline-local-auth:
    # useful when you run your Authorizer on separate Serverless file e.g. (Monorepo)
    lambdaEndpoint: http://127.0.0.1:10000
    # determine your target Lambda function name to proxy to. 
    lambdaAuthFnName: 'test'
    # determine the version of AWS-SDK to use in the proxy auth object
    lambdaVersion: 'v2'

provider:
  name: aws
  runtime: nodejs12.x
  endpointType: regional

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

functions:
  publicFunction:
    memorySize: 128
    timeout: 3
    handler: src/TestApi.handleRead
    events:
      - http:
          path: /public
          method: GET

  testFunction:
    memorySize: 128
    timeout: 3
    handler: src/TestApi.handleRead
    events:
      - http:
          path: /allow
          method: GET
          authorizer:
            type: CUSTOM
            authorizerId: "XXX"
          localAuthorizer:
            name: "autoLocalAuthProxy"
            type: "request"
      - http:
          path: /deny
          method: GET
          authorizer:
            type: CUSTOM
            authorizerId: "XXX"
          localAuthorizer:
            name: "autoLocalAuthProxy"
            type: "request"
